In [1]:
import numpy as np

In [7]:
# Load data
data = np.load('pareto_sensfunc1_run2.npy', allow_pickle=True)
data

array([nan])

In [8]:
# Load data
data = np.load('pareto_sensfunc2_run2.npy', allow_pickle=True)
data

array([nan])

In [6]:
# Load data
data = np.load('pareto_n_run2.npy', allow_pickle=True)
data

array([3.0303024])

In [7]:
paretoset_Sens1Pair1_final

array([[1.11111111e-01, 2.55842788e+00],
       [1.00000000e+00, 3.92867310e-16]])

In [8]:
# Load data
data = np.load('arpos_Paretos_Sens2_final.npz', allow_pickle=True)

# Extract data
for key, value in data.items():
    globals()[key] = value

# Print varaibles
for key in data.keys():
    print(key)

paretoset_Sens2Pair1_final


In [9]:
paretoset_Sens2Pair1_final

array([[1.11111111e-01, 2.55842788e+00],
       [1.00000000e+00, 3.92867310e-16]])

In [12]:
# Load data
data = np.load('arpos_Paretos_Param1_final.npz', allow_pickle=True)

# Extract data
for key, value in data.items():
    globals()[key] = value

# Print varaibles
for key in data.keys():
    print(key)

paretoset_Sens1mask1_Param_final


In [13]:
paretoset_Sens1mask1_Param_final

array([[0.01, 10.0],
       [50.0, 10.0]], dtype=object)